server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/vpp
    username: postgres
    password: ARM_Digigate

rms:
  jwt:
    secret: BackendServicesApiSystemSecRetKeyValue
    validation-time: 600000
    refresh-time: 86400000

  openapi:
    local-url: http://localhost:8080
    dev-url: http://localhost:8080